Codeartifact deploy
ClearlyEnergy/django-helpdesk pull request #23
Opened 2024-09-19 15:23 UTC by loydbanks

#### Any background context you want to provide?

#### What's this PR do?

#### When should it be merged in?

#### Do you want someone to review this before it gets merged in?

#### How should this be manually tested?

#### What are the relevant tickets?

#### Screenshots (if appropriate)

2024-09-19 15:41 UTC, paddatrapper requested changes

2024-09-19 15:41 UTC, paddatrapper commented on .github/workflows/codeartifact-deploy.yml
> +          python setup.py sdist
Don't call setup.py directly - you're removing it as part of the move to pyproject.toml

2024-09-19 15:41 UTC, paddatrapper commented on .github/workflows/codeartifact-deploy.yml
> +      - name: Publish Package
This task doesn't make sense - you're installing packages from the repo, not publishing to it

2024-09-19 15:41 UTC, paddatrapper commented on .github/workflows/codeartifact-deploy.yml
> +          python3 quicktest.py
?

2024-09-20 07:49 UTC, loydbanks commented on .github/workflows/codeartifact-deploy.yml
> +          python3 quicktest.py
According to the README file, this is how we run tests for this project.

2024-09-20 13:53 UTC, paddatrapper commented on .github/workflows/codeartifact-deploy.yml
> +          python3 quicktest.py
Why are you running tests at this point? This relates to https://github.com/ClearlyEnergy/django-helpdesk/pull/23#discussion_r1767059794

2024-10-02 07:58 UTC, paddatrapper commented on .github/workflows/codeartifact-deploy.yml
> +          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
If you're using OIDC, then these are not required

2024-10-04 16:21 UTC, paddatrapper approved these changes

2024-10-15 15:53 UTC, paddatrapper approved these changes

2024-10-16 08:48 UTC, merged