Ticket Forms: Add checkbox list input
ClearlyEnergy/django-helpdesk pull request #30
Opened 2024-10-10 15:03 UTC by iiloni-umd

#### What's this PR do?
Adds an input that allows users to specify a list of values to be shown in a list of checkboxes in a ticket form.

#### How should this be manually tested?
Edit a form to use the "Checkbox List" data type and add a few values to the list. Go to the ticket submission page and select a few checkboxes in that field and submit. In the created ticket, see the results as a list of values that were checked.

#### What are the relevant tickets?
https://clearlyenergy-inc.monday.com/boards/7029256041/pulses/6079186433

#### Screenshots (if appropriate)
![image](https://github.com/user-attachments/assets/410cb8ba-e8b1-463c-be9c-755bb1204468)
![image](https://github.com/user-attachments/assets/2e811841-050f-49df-a183-3151ec2d5934)

2024-12-13 21:52 UTC, ebeers-png commented
Looks great, my only suggestion would be to update how the values are displayed in the ticket table. Change from an array representation to just a comma-separated string.
![image](https://github.com/user-attachments/assets/a2423735-7490-4451-ae10-58dd94e748aa)
![image](https://github.com/user-attachments/assets/ba594e95-fa26-419d-bfc8-9592a906b7e6)

2024-12-13 21:53 UTC, ebeers-png requested changes
Looks great, my only suggestion would be to update how the values are displayed in the ticket table. Change from an array representation to just a comma-separated string.
![image](https://github.com/user-attachments/assets/a2423735-7490-4451-ae10-58dd94e748aa)
![image](https://github.com/user-attachments/assets/ba594e95-fa26-419d-bfc8-9592a906b7e6)

2024-12-18 15:47 UTC, iiloni-umd commented
That's a great idea! I updated both checkbox list and key value fields to have better formatting in the ticket data table.
![image](https://github.com/user-attachments/assets/e8437224-efc5-46d3-8a99-cb3c71526ac9)

2025-04-17 19:26 UTC, ebeers-png commented
Hey Itai, could you also update the formatting for the public ticket side as well?
![image](https://github.com/user-attachments/assets/6334e63c-a632-4356-acd7-90a6379c7710)

2025-04-18 15:25 UTC, iiloni-umd commented
I updated the object display to use the more elegant solution from the Key Value Text Field (#53) and added it to the public ticket view as well.

2025-04-22 19:15 UTC, ebeers-png commented
Thanks, it looks good! I noticed that as a side-effect, when I submit a ticket, edit it, and save it, it changes some blank fields to "None" - see images below. For this ticket, I didn't change anything when I saved it, I only opened up "Edit Ticket" and then scrolled to the bottom and saved it.

![image](https://github.com/user-attachments/assets/8fa0592b-66fb-41b3-98d9-2b4d6b20f766)
![image](https://github.com/user-attachments/assets/2ef0c072-7ace-485a-ae5e-1c26ec0ada4f)

As far as I can tell it doesn't affect anything - when I open up the Edit page again, those fields are still blank. So it should be fine? 

![image](https://github.com/user-attachments/assets/c6bafd63-64b4-4d31-bb2a-35e187c5a836)

2025-05-19 17:25 UTC, merged